XML format support: applied patch

diff --git a/lib/shunit2-2.1.6/src/shunit2 b/lib/shunit2-2.1.6/src/shunit2
--- a/lib/shunit2-2.1.6/src/shunit2
+++ b/lib/shunit2-2.1.6/src/shunit2
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 # $Id: shunit2 335 2011-05-01 20:10:33Z kate.ward@forestent.com $
 # vim:et:ft=sh:sts=2:sw=2
 #
@@ -25,9 +25,50 @@ SHUNIT_ERROR=2
 # enable strict mode by default
 SHUNIT_STRICT=${SHUNIT_STRICT:-${SHUNIT_TRUE}}
 
-_shunit_warn() { echo "shunit2:WARN $@" >&2; }
-_shunit_error() { echo "shunit2:ERROR $@" >&2; }
-_shunit_fatal() { echo "shunit2:FATAL $@" >&2; exit ${SHUNIT_ERROR}; }
+#_shunit_warn() { echo "shunit2:WARN $@" >&2; }
+#_shunit_error() { echo "shunit2:ERROR $@" >&2; }
+#_shunit_fatal() { echo "shunit2:FATAL $@" >&2; exit ${SHUNIT_ERROR}; }
+
+#
+# some convenient log functions
+#
+
+# log an expected failure into the test case error buffer
+_shunit_log_fail()
+{
+  _shunit_msg_=$1
+
+  __shunit_case_errors="${__shunit_case_errors}<failure type=\"${__SHUNIT_ASSERT_MSG_PREFIX}\" message=\"${_shunit_msg_}\"/>"
+
+  unset _shunit_msg_
+}
+
+# log an unexpected failure into the test case error buffer
+_shunit_log_error() 
+{
+  _level_=$1
+  shift
+
+  __shunit_case_errors="${__shunit_case_errors}<error type=\"${_level_}\">$@</error>";
+
+  unset _level_
+}
+
+_shunit_warn() { _shunit_log_error "WARN" $@; }
+_shunit_error() { _shunit_log_error "ERROR" $@; }
+_shunit_fatal() { _shunit_log_error "FATAL" $@; }
+
+# fake exit call to prevent scripts to echo escape prematurely
+# @NOTES:
+# 1. keep the function name for the trick to work
+# 2. tested script must be called directy by /bin/bash not a link to a shell, shabang is accepted
+exit()
+{
+  echo "exit builtin called with rc $1"
+}
+alias exit='exit'
+
+
 
 # specific shell checks
 if [ -n "${ZSH_VERSION:-}" ]; then
@@ -45,7 +86,8 @@ fi
 # constants
 #
 
-__SHUNIT_ASSERT_MSG_PREFIX='ASSERT:'
+__SHUNIT_ASSERT_MSG_PREFIX='shunit.ASSERT'
+#__SHUNIT_ASSERT_MSG_PREFIX='ASSERT:'
 __SHUNIT_MODE_SOURCED='sourced'
 __SHUNIT_MODE_STANDALONE='standalone'
 __SHUNIT_PARENT=${SHUNIT_PARENT:-$0}
@@ -72,6 +114,11 @@ __shunit_reportGenerated=${SHUNIT_FALSE}  # is report generated
 __shunit_script=''  # filename of unittest script (standalone mode)
 __shunit_skip=${SHUNIT_FALSE}  # is skipping enabled
 __shunit_suite=''  # suite of tests to execute
+__shunit_suite_name=''
+__shunit_cases=''
+__shunit_case_errors=''
+__shunit_system_out=''
+__shunit_system_err=''
 
 # counts of tests
 __shunit_testSuccess=${SHUNIT_TRUE}
@@ -84,6 +131,7 @@ __shunit_assertsTotal=0
 __shunit_assertsPassed=0
 __shunit_assertsFailed=0
 __shunit_assertsSkipped=0
+__shunit_assertsError=0
 
 # macros
 _SHUNIT_LINENO_='eval __shunit_lineno=""; if [ "${1:-}" = "--lineno" ]; then [ -n "$2" ] && __shunit_lineno="[$2] "; shift 2; fi'
@@ -104,8 +152,9 @@ assertEquals()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -lt 2 -o $# -gt 3 ]; then
-    _shunit_error "assertEquals() requires two or three arguments; $# given"
-    _shunit_error "1: ${1:+$1} 2: ${2:+$2} 3: ${3:+$3}${4:+ 4: $4}"
+#    _shunit_error "assertEquals() requires two or three arguments; $# given"
+#    _shunit_error "1: ${1:+$1} 2: ${2:+$2} 3: ${3:+$3}${4:+ 4: $4}"
+    _shunit_assertError "assertEquals() requires two or three arguments; $# given 1: ${1:+$1} 2: ${2:+$2} 3: ${3:+$3}"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -143,7 +192,8 @@ assertNotEquals()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -lt 2 -o $# -gt 3 ]; then
-    _shunit_error "assertNotEquals() requires two or three arguments; $# given"
+#    _shunit_error "assertNotEquals() requires two or three arguments; $# given"
+    _shunit_assertError "assertNotEquals() requires two or three arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -180,7 +230,8 @@ assertNull()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -lt 1 -o $# -gt 2 ]; then
-    _shunit_error "assertNull() requires one or two arguments; $# given"
+#    _shunit_error "assertNull() requires one or two arguments; $# given"
+    _shunit_assertError "assertNull() requires one or two arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -209,7 +260,8 @@ assertNotNull()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -gt 2 ]; then  # allowing 0 arguments as $1 might actually be null
-    _shunit_error "assertNotNull() requires one or two arguments; $# given"
+#    _shunit_error "assertNotNull() requires one or two arguments; $# given"
+    _shunit_assertError "assertNotNull() requires one or two arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -241,7 +293,8 @@ assertSame()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -lt 2 -o $# -gt 3 ]; then
-    _shunit_error "assertSame() requires two or three arguments; $# given"
+#    _shunit_error "assertSame() requires two or three arguments; $# given"
+    _shunit_assertError "assertSame() requires two or three arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -271,7 +324,8 @@ assertNotSame()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -lt 2 -o $# -gt 3 ]; then
-    _shunit_error "assertNotSame() requires two or three arguments; $# given"
+#    _shunit_error "assertNotSame() requires two or three arguments; $# given"
+    _shunit_assertError "assertNotSame() requires two or three arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -314,7 +368,8 @@ assertTrue()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -gt 2 ]; then
-    _shunit_error "assertTrue() takes one two arguments; $# given"
+#    _shunit_error "assertTrue() takes one two arguments; $# given"
+    _shunit_assertError "assertTrue() takes one two arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -379,7 +434,8 @@ assertFalse()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -lt 1 -o $# -gt 2 ]; then
-    _shunit_error "assertFalse() quires one or two arguments; $# given"
+#    _shunit_error "assertFalse() quires one or two arguments; $# given"
+    _shunit_assertError "assertFalse() requires one or two arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -433,7 +489,8 @@ fail()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -gt 1 ]; then
-    _shunit_error "fail() requires zero or one arguments; $# given"
+#    _shunit_error "fail() requires zero or one arguments; $# given"
+    _shunit_assertError "fail() requires zero or one arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -463,7 +520,8 @@ failNotEquals()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -lt 2 -o $# -gt 3 ]; then
-    _shunit_error "failNotEquals() requires one or two arguments; $# given"
+#    _shunit_error "failNotEquals() requires one or two arguments; $# given"
+    _shunit_assertError "failNotEquals() requires one or two arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -476,7 +534,8 @@ failNotEquals()
   shunit_expected_=$1
   shunit_actual_=$2
 
-  _shunit_assertFail "${shunit_message_:+${shunit_message_} }expected:<${shunit_expected_}> but was:<${shunit_actual_}>"
+#  _shunit_assertFail "${shunit_message_:+${shunit_message_} }expected:<${shunit_expected_}> but was:<${shunit_actual_}>"
+  _shunit_assertFail "${shunit_message_:+${shunit_message_} }expected:&lt;${shunit_unexpected_}&gt; but was:&lt;${shunit_actual_}&gt;"
 
   unset shunit_message_ shunit_expected_ shunit_actual_
   return ${SHUNIT_FALSE}
@@ -495,7 +554,8 @@ failSame()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -lt 2 -o $# -gt 3 ]; then
-    _shunit_error "failSame() requires two or three arguments; $# given"
+#    _shunit_error "failSame() requires two or three arguments; $# given"
+    _shunit_assertError "failSame() requires two or three arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -527,7 +587,8 @@ failNotSame()
 {
   ${_SHUNIT_LINENO_}
   if [ $# -lt 2 -o $# -gt 3 ]; then
-    _shunit_error "failNotEquals() requires one or two arguments; $# given"
+#    _shunit_error "failNotEquals() requires one or two arguments; $# given"
+    _shunit_assertError "failNotEquals() requires one or two arguments; $# given"
     return ${SHUNIT_ERROR}
   fi
   _shunit_shouldSkip && return ${SHUNIT_TRUE}
@@ -716,8 +777,8 @@ _shunit_mktempFunc()
   do
     _shunit_file_="${__shunit_tmpDir}/${_shunit_func_}"
     cat <<EOF >"${_shunit_file_}"
-#! /bin/sh
-exit ${SHUNIT_TRUE}
+#! /bin/bash
+builtin exit ${SHUNIT_TRUE}
 EOF
     chmod +x "${_shunit_file_}"
   done
@@ -756,11 +817,12 @@ _shunit_cleanup()
     # disable EXIT trap
     trap 0
     # add 128 to signal and exit
-    exit `expr ${_shunit_signal_} + 128`
+    builtin exit `expr ${_shunit_signal_} + 128`
   elif [ ${__shunit_reportGenerated} -eq ${SHUNIT_FALSE} ] ; then
-    _shunit_assertFail 'Unknown failure encountered running a test'
-    _shunit_generateReport
-    exit ${SHUNIT_ERROR}
+#    _shunit_assertFail 'Unknown failure encountered running a test'
+#    _shunit_generateReport
+#    exit ${SHUNIT_ERROR}
+    _shunit_assertError 'Unknown failure encountered running a test'
   fi
 
   unset _shunit_name_ _shunit_signal_
@@ -772,8 +834,13 @@ _shunit_cleanup()
 #   None
 _shunit_execSuite()
 {
-  for _shunit_test_ in ${__shunit_suite}; do
+  
+  # loop over test cases
+  for _shunit_case_ in ${__shunit_suite}; do
     __shunit_testSuccess=${SHUNIT_TRUE}
+
+    # reset test cases errors buffer
+    __shunit_case_errors=''
 
     # disable skipping
     endSkipping
@@ -781,9 +848,28 @@ _shunit_execSuite()
     # execute the per-test setup function
     setUp
 
+    # store the test case execution start time
+    _shunit_case_starttime_=$(date '+%s')
+
     # execute the test
-    echo "${_shunit_test_}"
-    eval ${_shunit_test_}
+    echo "${_shunit_case_}"
+#    eval ${_shunit_test_}
+    eval ${_shunit_case_}
+
+    # store the test case execution end time and duration
+    _shunit_case_endtime_=$(date '+%s')
+    _shunit_case_duration_=$(echo ${_shunit_case_endtime_} - ${_shunit_case_starttime_} | bc)
+
+    # check errors and output test case status
+    __shunit_cases="${__shunit_cases}
+  <testcase classname=\"${__shunit_suite_name}\" name=\"${_shunit_case_}\" time=\"${_shunit_case_duration_}\""
+
+    if [ -z "${__shunit_case_errors}" ]
+    then
+      __shunit_cases="${__shunit_cases}/>"
+    else
+      __shunit_cases="${__shunit_cases}>${__shunit_case_errors}</testcase>"
+    fi
 
     # execute the per-test tear-down function
     tearDown
@@ -796,7 +882,8 @@ _shunit_execSuite()
     fi
   done
 
-  unset _shunit_test_
+#  unset _shunit_test_
+  unset _shunit_case_
 }
 
 # Generates the user friendly report with appropriate OK/FAILED message.
@@ -807,40 +894,57 @@ _shunit_execSuite()
 #   string: the report of successful and failed tests, as well as totals.
 _shunit_generateReport()
 {
-  _shunit_ok_=${SHUNIT_TRUE}
+#  _shunit_ok_=${SHUNIT_TRUE}
+  _shunit_failures_=${__shunit_assertsFailed}
+  _shunit_skipped_=${__shunit_assertsSkipped}
+  _shunit_errors_=${__shunit_assertsError}
 
-  # if no exit code was provided one, determine an appropriate one
-  [ ${__shunit_testsFailed} -gt 0 \
-      -o ${__shunit_testSuccess} -eq ${SHUNIT_FALSE} ] \
-          && _shunit_ok_=${SHUNIT_FALSE}
+#  # if no exit code was provided one, determine an appropriate one
+#  [ ${__shunit_testsFailed} -gt 0 \
+#      -o ${__shunit_testSuccess} -eq ${SHUNIT_FALSE} ] \
+#          && _shunit_ok_=${SHUNIT_FALSE}
 
-  echo
-  if [ ${__shunit_testsTotal} -eq 1 ]; then
-    echo "Ran ${__shunit_testsTotal} test."
-  else
-    echo "Ran ${__shunit_testsTotal} tests."
-  fi
+  cat << EOF
+<?xml version="1.0" encoding="UTF-8"?>
+<testsuite errors="${_shunit_errors_}" failures="${_shunit_failures_}" hostname="$(hostname)" name="${__shunit_suite_name}" tests="${__shunit_testsTotal}" time="${__shunit_suite_duration}" timestamp="${__shunit_suite_timestamp}">
+  ${__shunit_cases}
+  <properties>${_shunit_env_}</properties>
+  <system-out><![CDATA[$(cat ${__shunit_system_out} | sed 's/</&lg;/g;s/>/&gt;/g')]]></system-out>
+  <system-err><![CDATA[$(cat ${__shunit_system_err} | sed 's/</&lg;/g;s/>/&gt;/g')]]></system-err>
+</testsuite>
+EOF
 
-  _shunit_failures_=''
-  _shunit_skipped_=''
-  [ ${__shunit_assertsFailed} -gt 0 ] \
-      && _shunit_failures_="failures=${__shunit_assertsFailed}"
-  [ ${__shunit_assertsSkipped} -gt 0 ] \
-      && _shunit_skipped_="skipped=${__shunit_assertsSkipped}"
+#  echo
+#  if [ ${__shunit_testsTotal} -eq 1 ]; then
+#    echo "Ran ${__shunit_testsTotal} test."
+#  else
+#    echo "Ran ${__shunit_testsTotal} tests."
+#  fi
+  # cleanup buffer files
+  rm -f ${__shunit_system_out}
+  rm -f ${__shunit_system_err}
+ 
 
-  if [ ${_shunit_ok_} -eq ${SHUNIT_TRUE} ]; then
-    _shunit_msg_='OK'
-    [ -n "${_shunit_skipped_}" ] \
-        && _shunit_msg_="${_shunit_msg_} (${_shunit_skipped_})"
-  else
-    _shunit_msg_="FAILED (${_shunit_failures_}"
-    [ -n "${_shunit_skipped_}" ] \
-        && _shunit_msg_="${_shunit_msg_},${_shunit_skipped_}"
-    _shunit_msg_="${_shunit_msg_})"
-  fi
-
-  echo
-  echo ${_shunit_msg_}
+#  _shunit_failures_=''
+#  _shunit_skipped_=''
+#  [ ${__shunit_assertsFailed} -gt 0 ] \
+#      && _shunit_failures_="failures=${__shunit_assertsFailed}"
+#  [ ${__shunit_assertsSkipped} -gt 0 ] \
+#      && _shunit_skipped_="skipped=${__shunit_assertsSkipped}"
+#
+#  if [ ${_shunit_ok_} -eq ${SHUNIT_TRUE} ]; then
+#    _shunit_msg_='OK'
+#    [ -n "${_shunit_skipped_}" ] \
+#        && _shunit_msg_="${_shunit_msg_} (${_shunit_skipped_})"
+#  else
+#    _shunit_msg_="FAILED (${_shunit_failures_}"
+#    [ -n "${_shunit_skipped_}" ] \
+#        && _shunit_msg_="${_shunit_msg_},${_shunit_skipped_}"
+#    _shunit_msg_="${_shunit_msg_})"
+#  fi
+#
+#  echo
+#  echo ${_shunit_msg_}
   __shunit_reportGenerated=${SHUNIT_TRUE}
 
   unset _shunit_failures_ _shunit_msg_ _shunit_ok_ _shunit_skipped_
@@ -879,7 +983,8 @@ _shunit_assertFail()
   __shunit_testSuccess=${SHUNIT_FALSE}
   __shunit_assertsFailed=`expr ${__shunit_assertsFailed} + 1`
   __shunit_assertsTotal=`expr ${__shunit_assertsTotal} + 1`
-  echo "${__SHUNIT_ASSERT_MSG_PREFIX}${_shunit_msg_}"
+#  echo "${__SHUNIT_ASSERT_MSG_PREFIX}${_shunit_msg_}"
+  __shunit_case_errors="${__shunit_case_errors}<failure type=\"${__SHUNIT_ASSERT_MSG_PREFIX}\" message=\"${_shunit_msg_}\"/>"
 
   unset _shunit_msg_
 }
@@ -893,6 +998,20 @@ _shunit_assertSkip()
   __shunit_assertsSkipped=`expr ${__shunit_assertsSkipped} + 1`
   __shunit_assertsTotal=`expr ${__shunit_assertsTotal} + 1`
 }
+
+
+_shunit_assertError()
+{
+  _shunit_msg_=$1
+
+  __shunit_assertsError=`expr ${__shunit_assertsError} + 1`
+  __shunit_assertsTotal=`expr ${__shunit_assertsTotal} + 1`
+  _shunit_error "${__SHUNIT_ASSERT_MSG_PREFIX}: ${_shunit_msg_}"
+
+  unset _shunit_msg_
+}
+
+
 
 # Prepare a script filename for sourcing.
 #
@@ -1018,12 +1137,22 @@ if [ "${__shunit_mode}" = "${__SHUNIT_MODE_STANDALONE}" ]; then
   . "`_shunit_prepForSourcing \"${__shunit_script}\"`"
 fi
 
+#  for _shunit_test_ in ${__shunit_suite}; do
+# create buffer files for stdout and stderr
+
+__shunit_system_out=$(mktemp 'shunit-out.XXXX')
+__shunit_system_err=$(mktemp 'shunit-err.XXXX')
+
+# alter file descriptors
+exec 6>&1 7>&2
+exec >> ${__shunit_system_out} 2>> ${__shunit_system_err}
+
 # execute the oneTimeSetUp function (if it exists)
-oneTimeSetUp
+oneTimeSetUp | tee -a ${__shunit_system_out} 2>&1
 
 # execute the suite function defined in the parent test script
 # deprecated as of 2.1.0
-suite
+suite | tee -a ${__shunit_system_out} 2>&1
 
 # if no suite function was defined, dynamically build a list of functions
 if [ -z "${__shunit_suite}" ]; then
@@ -1034,15 +1163,39 @@ if [ -z "${__shunit_suite}" ]; then
 fi
 unset shunit_func_ shunit_funcs_
 
+# get test suite name
+__shunit_suite_name=$(basename $0 | sed 's/\..*$//')
+
+# get environment
+#_shunit_env_=$(env | sed 's!=!" value="!;s!^!<property name="!;s!$!"/>!')
+
+# store the test suite execution date and start time
+__shunit_suite_timestamp=$(date -u '+%Y-%m-%dT%T')
+__shunit_suite_starttime=$(date '+%s')
+
 # execute the tests
 _shunit_execSuite
 
+# store the test suite execution end time and duration
+__shunit_suite_endtime=$(date '+%s')
+__shunit_suite_duration=$(echo ${__shunit_suite_endtime} - ${__shunit_suite_starttime} | bc)
+
 # execute the oneTimeTearDown function (if it exists)
-oneTimeTearDown
+oneTimeTearDown | tee -a ${__shunit_system_out} 2>&1
+
+# restore file descriptors
+exec 1>&6 2>&7
+exec 6>&- 7>&-
 
 # generate the report
-_shunit_generateReport
+#_shunit_generateReport
+if [ -n "${SHUNIT_OUTPUTDIR}" ]
+then
+  _shunit_generateReport > "${SHUNIT_OUTPUTDIR}/TEST-${__shunit_suite_name}.xml"
+else
+  _shunit_generateReport
+fi
 
 # that's it folks
 [ ${__shunit_testsFailed} -eq 0 ]
-exit $?
+builtin exit $?
